name: JavaScript CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x, 18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
        shell: bash
      - name: Test
        run: yarn vitest run
        shell: bash
